# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks

# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent


# Global properties
#
# The top properties below are applied to every block, but can be overridden.
separator=true
separator_block_width=20
markup=pango

# Directorio cos scripts
SCRIPT_DIR=/home/anxo/.config/scripts

#[documentation]
#full_text=Documentation
#website=https://vivien.github.io/i3blocks
#command=xdg-open "$website"
#color=#f12711
#
#[greetings]
#color=#f5af19
#command=echo "Hello, $USER!"
#interval=once

#[time]
#command=date '+%d-%m-%Y %H:%M:%S'
#interval=1

[memory]
command=${SCRIPT_DIR}/memoria
interval=1
LABEL= 

[cpu_usage]
command=${SCRIPT_DIR}/cpu_usage
interval=1

[battery2]
command=${SCRIPT_DIR}/bateria
interval=10

[calendario]
command=${SCRIPT_DIR}/calendario
interval=60
HEIGHT=180
WIDTH=220

[reloxo]
command=${SCRIPT_DIR}/reloxo
interval=1

[shutdown_menu]
full_text=<span color="#FF0000"></span> 
# If you are using FontAwesome, we recommend the power-off icon:
# http://fontawesome.io/icon/power-off/
command=$SCRIPT_DIR/shutdown_menu
#FG_COLOR=#bbbbbb
#BG_COLOR=#111111
#HLFG_COLOR=#111111
#HLBG_COLOR=#bbbbbb
#BORDER_COLOR=#222222
#ROFI_TEXT=Menu:
#ROFI_OPTIONS=-width 11 -location 3 -hide-scrollbar -bw 2
#ZENITY_TITLE=Menu
#ZENITY_TEXT=Action:
#ZENITY_OPTIONS=--column= --hide-header
ENABLE_CONFIRMATIONS=true # (must be true or false)
#LAUNCHER=rofi (must be rofi or zenity)
#LOCKSCRIPT=i3lock --color=${BG_COLOR#"#"}
