# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks

# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent


# Global properties
#
# The top properties below are applied to every block, but can be overridden.
separator=true
separator_block_width=20
markup=pango

# Directorio cos scripts
SCRIPT_DIR=/home/anxo/.config/scripts

#[documentation]
#full_text=Documentation
#website=https://vivien.github.io/i3blocks
#command=xdg-open "$website"
#color=#f12711
#
#[greetings]
#color=#f5af19
#command=echo "Hello, $USER!"
#interval=once

#[time]
#command=date '+%d-%m-%Y %H:%M:%S'
#interval=1

[memory]
command=${SCRIPT_DIR}/memoria
interval=1
LABEL= 

[cpu_usage]
command=${SCRIPT_DIR}/cpu_usage
interval=1

[battery2]
command=${SCRIPT_DIR}/bateria
interval=10

[calendario]
command=${SCRIPT_DIR}/calendario
interval=60
HEIGHT=180
WIDTH=220

[reloxo]
command=${SCRIPT_DIR}/reloxo
interval=1

