# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

#general {
#        colors = true
#        interval = 5
#}
#
#order += "ipv6"
#order += "wireless _first_"
#order += "ethernet _first_"
#order += "battery all"
#order += "disk /"
#order += "load"
#order += "memory"
#order += "tztime local"
#
#wireless _first_ {
#        format_up = "W: (%quality at %essid) %ip"
#        format_down = "W: down"
#}
#
#ethernet _first_ {
#        format_up = "E: %ip (%speed)"
#        format_down = "E: down"
#}
#
#battery all {
#        format = "%status %percentage %remaining"
#}
#
#disk "/" {
#        format = "%avail"
#}
#
#load {
#        format = "%1min"
#}
#
#memory {
#        format = "%used | %available"
#        threshold_degraded = "1G"
#        format_degraded = "MEMORY < %available"
#}
#
#tztime local {
#        format = "%Y-%m-%d %H:%M:%S"
#}

general {
        colors = true
        interval = 1
        output_format = "i3bar"
	color_separator = "#00FF00"
}

#order += "ipv6"
order += "wireless _first_"
order += "ethernet _first_"
order += "battery all"
#order += "disk /"
#order += "load"
order += "memory"
order += "cpu_usage"
order += "cpu_temperature thresholds"
order += "tztime local"

wireless _first_ {
#        format_up = "Wl: (%quality at %essid) %ip"
        format_up = " %bitrate at %essid"
        format_down = " down"
}

ethernet _first_ {
        format_up = " %ip (%speed)"
        format_down = " down"
        separator_block_width = 20
}

battery all {
        format = "%status %percentage %remaining"
        separator_block_width = 20
	format_percentage = "%.00f%s"
	#last_full_capacity = true
	low_threshold = 10
	threshold_type = percentage
	status_bat = ""
	status_chr = ""
	status_full = ""
}

disk "/" {
        format = "%avail"
}

load {
        format = "%1min"
}

memory {
        format = " %used|%available"
        threshold_degraded = "4G"
        format_degraded = "MEMORY < %available"
        threshold_critical = "1G"
        separator_block_width = 20
}

cpu_usage {
        format = "%usage"
        max_threshold = 90
        separator = false
	degraded_threshold = 60
}

cpu_temperature thresholds {
        format = "%degrees ºC"
        #degraded_threshold = 60
        max_threshold = 75
        separator_block_width = 20
}

tztime local {
        format = "  %d-%m-%Y %H:%M:%S "
}
