[greeter]
#background = /etc/lightdm/media/Wallpaper02.jpg
background = /etc/lightdm/media/bosque.png
theme-name = adw-gtk3-dark
font-name = Sans 16
#position = 30% 50%
default-user-image = /etc/lightdm/media/cute_ghost.jpg

