#!/bin/bash

WIDTH=${WIDTH:-200}
HEIGHT=${HEIGHT:-200}
DATAFMT=${DATAFMT:-"+%a %d.%m.%Y"}
#HORAFMT=${HORAFMT:-"+%H:%M:%S"}
DATALABEL=${DATALABEL:-}
#HORALABEL=${HORALABLE:-}

# rosa clasico
color=#fbcce7
# cotton candy
datacor=#ffbcd9
# Orquidea escuro
horacor=#9932cc
horacor=#966fd6
# salmon escuro
horacor=#e9967a
# rosa fucsia
horacor=#ff77ff
#echo "<span color=\"${datacor}\">${DATALABEL}</span> $(LANG=gl_ES.UTF-8 date "$DATAFMT") <span color=\"${horacor}\">${HORALABEL}</span> $(LANG=gl_ES.UTF-8 date "$HORAFMT")"
echo "<span color=\"${datacor}\">${DATALABEL}</span> $(LANG=gl_ES.UTF-8 date "$DATAFMT")"
#echo "<span color=\"${horacor}\">${HORALABEL}</span>$(LANG=gl_ES.UTF-8 date "$HORAFMT")"
echo "<span color=\"${datacor}\">${DATALABEL}</span>$(LANG=gl_ES.UTF-8 date "$DATAFMT")"


